[package]
edition = "2018"
name = "replace"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
derive = ["replace_derive"]

[dependencies]
replace_derive = {path = "replace_derive", optional = true}
